# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name='auth.proto',
    package='',
    syntax='proto3',
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\nauth.proto\"7\n\x10\x43heckRoleRequest\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\r\n\x05roles\x18\x02 \x03(\t\"3\n\x11\x43heckRoleResponse\x12\x0e\n\x06result\x18\x01 \x01(\x08\x12\x0e\n\x06status\x18\x02 \x01(\t2<\n\x04\x41uth\x12\x34\n\tCheckRole\x12\x11.CheckRoleRequest\x1a\x12.CheckRoleResponse\"\x00\x62\x06proto3',
)


_CHECKROLEREQUEST = _descriptor.Descriptor(
    name='CheckRoleRequest',
    full_name='CheckRoleRequest',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='access_token',
            full_name='CheckRoleRequest.access_token',
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode('utf-8'),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name='roles',
            full_name='CheckRoleRequest.roles',
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[],
    serialized_start=14,
    serialized_end=69,
)


_CHECKROLERESPONSE = _descriptor.Descriptor(
    name='CheckRoleResponse',
    full_name='CheckRoleResponse',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='result',
            full_name='CheckRoleResponse.result',
            index=0,
            number=1,
            type=8,
            cpp_type=7,
            label=1,
            has_default_value=False,
            default_value=False,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name='status',
            full_name='CheckRoleResponse.status',
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode('utf-8'),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[],
    serialized_start=71,
    serialized_end=122,
)

DESCRIPTOR.message_types_by_name['CheckRoleRequest'] = _CHECKROLEREQUEST
DESCRIPTOR.message_types_by_name['CheckRoleResponse'] = _CHECKROLERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CheckRoleRequest = _reflection.GeneratedProtocolMessageType(
    'CheckRoleRequest',
    (_message.Message,),
    {
        'DESCRIPTOR': _CHECKROLEREQUEST,
        '__module__': 'auth_pb2'
        # @@protoc_insertion_point(class_scope:CheckRoleRequest)
    },
)
_sym_db.RegisterMessage(CheckRoleRequest)

CheckRoleResponse = _reflection.GeneratedProtocolMessageType(
    'CheckRoleResponse',
    (_message.Message,),
    {
        'DESCRIPTOR': _CHECKROLERESPONSE,
        '__module__': 'auth_pb2'
        # @@protoc_insertion_point(class_scope:CheckRoleResponse)
    },
)
_sym_db.RegisterMessage(CheckRoleResponse)


_AUTH = _descriptor.ServiceDescriptor(
    name='Auth',
    full_name='Auth',
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=124,
    serialized_end=184,
    methods=[
        _descriptor.MethodDescriptor(
            name='CheckRole',
            full_name='Auth.CheckRole',
            index=0,
            containing_service=None,
            input_type=_CHECKROLEREQUEST,
            output_type=_CHECKROLERESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_AUTH)

DESCRIPTOR.services_by_name['Auth'] = _AUTH

# @@protoc_insertion_point(module_scope)
